# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Upload to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
      #- codebuild-github-actions-practice-${{ github.run_id }}-${{ github.run_attempt }}
    environment: test
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package in editable mode with dev dependencies
        pip install -e ".[dev]"
        pip install build

    - name: Lint with ruff
      run: |
        ruff check

    - name: Test with pytest
      run: |
        pytest -v --cov=file_encoder --cov-report=xml --cov-report=term-missing > pytest-output.txt 2>&1

    - name: Build package
      run: |
        python -m build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: matrix.python-version == '3.13'
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Upload wheel to S3
      if: matrix.python-version == '3.13'
      run: |
        for file in dist/*.whl; do
          if [ -f "$file" ]; then
            aws s3 cp "$file" s3://${{ secrets.AWS_S3_BUCKET }}/wheels/
          fi
        done

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: matrix.python-version == '3.13'
      with:
        name: test-results
        path: |
          pytest-output.txt
          coverage.xml
        retention-days: 30

    - name: Configure CodeArtifact
      if: matrix.python-version == '3.13'
      run: |
        # Get CodeArtifact authorization token
        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain zabalytics --query authorizationToken --output text)

        # Configure pip to use CodeArtifact
        aws codeartifact login --tool pip --domain zabalytics --repository pypi

        # Configure twine for publishing
        pip install twine

        # Get the repository endpoint
        export CODEARTIFACT_REPOSITORY_URL=$(aws codeartifact get-repository-endpoint --domain zabalytics --repository pypi --format pypi --query repositoryEndpoint --output text)

        echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV
        echo "CODEARTIFACT_REPOSITORY_URL=$CODEARTIFACT_REPOSITORY_URL" >> $GITHUB_ENV

    - name: Publish to CodeArtifact
      if: matrix.python-version == '3.13'
      run: |
        twine upload --repository-url $CODEARTIFACT_REPOSITORY_URL/simple/ \
          --username aws \
          --password $CODEARTIFACT_AUTH_TOKEN \
          dist/*.whl
